source 'https://github.com/CocoaPods/Specs.git'

target 'JobKit' do
  pod "JobKit", :path => "../"
end

target 'Tests' do
  #pod "JobKit", :path => "../"
  pod 'Realm/Headers'
  pod 'OCMock'
  pod 'Expecta'
end
